### ISSUE TITLE
One problem about the stargan distillation

### ISSUE THREAD

**Issue by LGYoung** [stanford-futuredata/lit-code#1]
Hello, I followed ur instruction and tried to train StarGAN student model, but got an error as follows:
~~~
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    main(config)
  File "main.py", line 40, in main
    solver = Solver(celeba_loader, rafd_loader, config)
  File "solver.py", line 78, in __init__
    self.build_model()
  File "solver.py", line 96, in build_model
    self.restore_model()
  File "lit-code/stargan/solver.py", line 129, in restore_model
    self.G.load_state_dict(torch.load(G_student_path, map_location=lambda storage, loc: storage))
  File "torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'stargan_models/student-G2.ckpt'
~~~
I think there are some mistakes in ur 'restore_model' function:
Does the 'resume_iters' parameter really work?
Does it need to load student model while training?
Hope for ur answering.

**Comment by ddkang** [comment]
Please past the full command line you are using, along with all relevant software versions.

**Comment by LGYoung** [comment]
I used the following command line to train:
`
CUDA_VISIBLE_DEVICES=2 python main.py  --mode train --dataset CelebA --image_size 128 
--c_dim 5 --sample_dir stargan_celeba/samples --log_dir stargan_celeba/logs --result_dir stargan_celeba/results --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young 
--model_save_dir stargan_models --g_repeat_num 2
`
and the software versions is as follows:
pytorch  0.4.1
cudatoolkit 9.0

I think the restore_model() part doesn't need to restore student model while training. So I commented it during training and uncommented it during test. It works well

**Comment by ddkang** [comment]
Great, thanks.

I also believe pytorch 1.0+ should work better.
